# Generated by Django 3.0.2 on 2020-02-11 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure_app', '0001_initial'),
        ('financial_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=255, null=True)),
                ('real_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rised_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='asset_images')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='basic_asset_createdby', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='division', to='structure_app.Division')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='basic_asset_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255, null=True)),
                ('unit_size', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('size', models.PositiveIntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Commodity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_createdby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='size_type_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_category_createdby', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_app.Product_category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categories', models.ManyToManyField(db_table='product_app_product_categories', to='product_app.Product_category')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_product', to='structure_app.Client')),
                ('commodities', models.ManyToManyField(through='product_app.Ingredient', to='product_app.Commodity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Product'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='size_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product_app.Size_type'),
        ),
        migrations.CreateModel(
            name='Commodity_transfer_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commodity_transfer_type_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commodity_transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=0)),
                ('recieved_ebarimt', models.BooleanField(default=0)),
                ('comment', models.TextField(null=True)),
                ('quantity_residuals', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_deducted', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_increased', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_balance', models.PositiveIntegerField(blank=True, null=True)),
                ('size_residuals', models.PositiveIntegerField(blank=True, null=True)),
                ('size_deducted', models.PositiveIntegerField(blank=True, null=True)),
                ('size_increased', models.PositiveIntegerField(blank=True, null=True)),
                ('size_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='financial_app.Budget')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product_app.Commodity')),
                ('commodity_transfer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_type', to='product_app.Commodity_transfer_type')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='confirmed_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commodity_transfer_createdby', to=settings.AUTH_USER_MODEL)),
                ('fr_division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fr_division', to='structure_app.Division')),
                ('fr_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fr_user', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_app.Store')),
                ('to_division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_division', to='structure_app.Division')),
                ('to_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product_app.Product')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commodity_transfer_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commodity_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('Division', models.ManyToManyField(db_table='product_app_division_commodity_categories', to='structure_app.Division')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commodity_category_createdby', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_app.Commodity_category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='categories',
            field=models.ManyToManyField(db_table='product_app_commodity_categories', to='product_app.Commodity_category'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commodity_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commodity',
            name='size_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product_app.Size_type'),
        ),
        migrations.CreateModel(
            name='broken_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('size', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=255, null=True)),
                ('damage_paid', models.BooleanField(default=0)),
                ('money_transfer_status', models.CharField(default='тодорхойгүй', max_length=30)),
                ('basic_asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='broken_basic_asset', to='product_app.Basic_asset')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='broken_commodity', to='product_app.Commodity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='broken_item_createdby', to=settings.AUTH_USER_MODEL)),
                ('money_transfer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='broken_item_money', to='financial_app.Money_transfer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='broken_product', to='product_app.Product')),
                ('size_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product_app.Size_type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='broken_item_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Basic_asset_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('counted_day', models.DateField()),
                ('prev_quantity', models.PositiveIntegerField()),
                ('quantity_balance', models.PositiveIntegerField()),
                ('quantity_increased', models.PositiveIntegerField()),
                ('quantity_deducted', models.PositiveIntegerField()),
                ('information', models.TextField(null=True)),
                ('controll_confirmed', models.BooleanField(default=0)),
                ('basic_asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='counts', to='product_app.Basic_asset')),
                ('controlled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='controlled_by', to=settings.AUTH_USER_MODEL)),
                ('counted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='counted_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='basic_asset_count_createdby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='basic_asset_count_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('commodity', 'product')},
        ),
    ]
