# Generated by Django 3.0.2 on 2020-02-13 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0007_auto_20200212_1924'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_transfer',
            name='order_detial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commodity_transfers', to='payment_app.Order_detial'),
        ),
    ]
