# Generated by Django 3.0.2 on 2020-02-13 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0002_auto_20200211_1723'),
        ('structure_app', '0009_delete_hotel_client_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_app', '0002_commodity_transfer_order_detial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_transfer',
            name='fr_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sending_commodity_transfers', to='structure_app.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodity_transfer',
            name='to_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coming_commodity_transfers', to='structure_app.Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basic_asset',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='basic_assets', to='structure_app.Division'),
        ),
        migrations.AlterField(
            model_name='broken_item',
            name='basic_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='broken_basic_assets', to='product_app.Basic_asset'),
        ),
        migrations.AlterField(
            model_name='broken_item',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='broken_commodities', to='product_app.Commodity'),
        ),
        migrations.AlterField(
            model_name='broken_item',
            name='money_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='broken_items_money', to='financial_app.Money_transfer'),
        ),
        migrations.AlterField(
            model_name='broken_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='broken_products', to='product_app.Product'),
        ),
        migrations.AlterField(
            model_name='broken_item',
            name='size_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='broken_items', to='product_app.Size_type'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='size_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commodities', to='product_app.Size_type'),
        ),
        migrations.AlterField(
            model_name='commodity_category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_categories', to='product_app.Commodity_category'),
        ),
        migrations.AlterField(
            model_name='commodity_transfer',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='budget_commodities', to='financial_app.Budget'),
        ),
        migrations.AlterField(
            model_name='commodity_transfer',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers', to='product_app.Commodity'),
        ),
        migrations.AlterField(
            model_name='commodity_transfer',
            name='commodity_transfer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commodity_transfers', to='product_app.Commodity_transfer_type'),
        ),
        migrations.AlterField(
            model_name='commodity_transfer',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commodity_transfer_confirmed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commodity_transfer',
            name='fr_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sending_commodity_transfers', to='structure_app.Division'),
        ),
        migrations.AlterField(
            model_name='commodity_transfer',
            name='fr_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sending_commodity_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commodity_transfer',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bought_commodities', to='product_app.Store'),
        ),
        migrations.AlterField(
            model_name='commodity_transfer',
            name='to_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coming_commodity_transfers', to='structure_app.Division'),
        ),
        migrations.AlterField(
            model_name='commodity_transfer',
            name='to_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coming_commodity_transfers', to='product_app.Product'),
        ),
        migrations.AlterField(
            model_name='commodity_transfer',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coming_commodity_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='size_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredients', to='product_app.Size_type'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_categories', to='product_app.Product_category'),
        ),
    ]
