# Generated by Django 3.0.2 on 2020-02-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0010_auto_20200215_1631'),
        ('product_app', '0006_auto_20200216_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity_transfer',
            name='fr_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sending_commodity_transfers', to='structure_app.Client'),
        ),
    ]
