# Generated by Django 3.0.2 on 2020-02-19 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_app', '0013_auto_20200216_1859'),
        ('structure_app', '0010_auto_20200215_1631'),
        ('financial_app', '0003_auto_20200216_1859'),
        ('product_app', '0008_auto_20200219_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=0)),
                ('recieved_ebarimt', models.BooleanField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('unit_size', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item_transfer_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_transfer_type_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='commodity_transfer_type',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='product_app.Commodity'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='product_app.Product'),
        ),
        migrations.DeleteModel(
            name='Commodity_transfer',
        ),
        migrations.DeleteModel(
            name='Commodity_transfer_type',
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='Item_transfer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_transfers', to='product_app.Item_transfer_type'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bought_item_transfers', to='financial_app.Budget'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers', to='product_app.Commodity'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_transfer_confirmed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_transfer_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='fr_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sending_item_transfers', to='structure_app.Client'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='fr_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sending_item_transfers', to='structure_app.Division'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='fr_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sending_item_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='order_detial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_transfers', to='payment_app.Order_detial'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers', to='product_app.Product'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bought_item_transfers', to='product_app.Store'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='to_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coming_item_transfers', to='structure_app.Client'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='to_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coming_item_transfers', to='structure_app.Division'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='to_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredients_transfer', to='product_app.Product'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coming_item_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_transfer_modifiedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
