# Generated by Django 3.0.2 on 2020-02-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_auto_20200219_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_transfer',
            name='Item_transfer_type',
        ),
    ]
