# Generated by Django 3.0.2 on 2020-02-19 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_remove_item_transfer_item_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_transfer',
            name='item_transfer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='item_transfers', to='product_app.Item_transfer_type'),
            preserve_default=False,
        ),
    ]
