# Generated by Django 3.0.2 on 2020-05-03 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_app', '0014_auto_20200309_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_transfer',
            name='fr_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sending_item_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item_transfer',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coming_item_transfers', to=settings.AUTH_USER_MODEL),
        ),
    ]
