# Generated by Django 3.0.2 on 2020-05-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0017_auto_20200503_1830'),
    ]

    operations = [
    ]
