# Generated by Django 3.0.2 on 2020-05-03 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0019_auto_20200425_1715'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_app', '0018_auto_20200503_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commodity_balances', to='structure_app.Client')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='balances', to='product_app.Commodity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_balance_createdby', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commodity_balances', to='structure_app.Division')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='balances', to='product_app.Product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_balance_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commodity_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='item_transfer',
            name='size_type',
        ),
        migrations.DeleteModel(
            name='Commodity_balance',
        ),
    ]
