# Generated by Django 3.0.2 on 2020-05-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0019_auto_20200503_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='description',
            new_name='store_info',
        ),
    ]
