# Generated by Django 3.0.2 on 2020-05-08 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0020_auto_20200505_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_balance',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='balances', to='product_app.Commodity'),
        ),
    ]
