# Generated by Django 3.0.2 on 2020-05-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0021_auto_20200508_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_balance',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_balance',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
