# Generated by Django 3.0.2 on 2020-05-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0020_auto_20200509_1145'),
        ('product_app', '0024_auto_20200510_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_transfer',
            name='to_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coming_item_transfers', to='structure_app.Division'),
        ),
    ]
