# Generated by Django 3.0.2 on 2020-02-13 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_app', '0001_initial'),
        ('structure_app', '0009_delete_hotel_client_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_client_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices_type', models.CharField(choices=[('0', '---'), ('1', 'Зочины мэдээлэл'), ('2', 'Цэвэрлэгээний мэдээлэл'), ('3', 'Мини барны мэдээлэл')], default=0, max_length=3)),
                ('login_info_choices', models.CharField(choices=[('0', '---'), ('in', 'Зочин орсон'), ('out', 'Зочин гарсан')], default=0, max_length=3)),
                ('cleaning_info_choices', models.CharField(choices=[('0', '---'), ('c_s', 'Цэвэрлэж эхэлсэн'), ('c_e', 'Цэвэрлэж дууссан')], default=0, max_length=3)),
                ('bar_refilled_info_choices', models.CharField(choices=[('0', '---'), ('b_r', 'Мини бар цэнэглэгдсэн'), ('b_u', 'Мини бар цэнэглэгдээгүй')], default=0, max_length=3)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('limit_time', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='structure_app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_client_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_items', to='structure_app.Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_items', to='product_app.Product')),
            ],
        ),
    ]
