# Generated by Django 3.0.2 on 2020-06-20 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_client_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_client_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices_type', models.CharField(choices=[('1', 'Өрөөний мэдээлэл'), ('2', 'Зочины тоон мэдээлэл'), ('3', 'Цэвэрлэгээний мэдээлэл'), ('4', 'Мини барны мэдээлэл')], max_length=3)),
                ('value', models.CharField(max_length=3)),
                ('number', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='structure_app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_client_item_eelj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_items_eelj', to='structure_app.Client')),
            ],
        ),
    ]
