# Generated by Django 3.0.2 on 2020-06-20 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_app', '0001_initial'),
        ('hotel', '0001_initial'),
        ('structure_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_client_item_eelj',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_items_eelj', to='product_app.Product'),
        ),
        migrations.AddField(
            model_name='hotel_client_item',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_items', to='structure_app.Client'),
        ),
        migrations.AddField(
            model_name='hotel_client_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_items', to='product_app.Product'),
        ),
    ]
