# Generated by Django 3.0.2 on 2020-06-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200620_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_client_log',
            name='choices_type',
            field=models.CharField(max_length=3),
        ),
    ]
