# Generated by Django 3.0.2 on 2020-03-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200313_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_client_log',
            name='bar_refilled_info_choices',
        ),
        migrations.RemoveField(
            model_name='hotel_client_log',
            name='cleaning_info_choices',
        ),
        migrations.RemoveField(
            model_name='hotel_client_log',
            name='login_info_choices',
        ),
        migrations.RemoveField(
            model_name='hotel_client_log',
            name='room_info_choices',
        ),
        migrations.AddField(
            model_name='hotel_client_log',
            name='value',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
