# Generated by Django 3.0.2 on 2020-02-11 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0005_user_profile_avatar'),
        ('financial_app', '0002_auto_20200211_1723'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_app', '0001_initial'),
        ('payment_app', '0002_auto_20200211_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos_account_consolidation',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pos_account_consolidations', to='structure_app.Division'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='structure_app.Client'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='structure_app.Customer'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='structure_app.Division'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='payment_app.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='structure_app.Client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='structure_app.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='structure_app.Division'),
        ),
        migrations.AlterField(
            model_name='order_detial',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detials', to='payment_app.Order'),
        ),
        migrations.AlterField(
            model_name='order_detial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detials', to='product_app.Product'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payment_app.Bill'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='wallet',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='financial_app.Wallet'),
        ),
        migrations.AlterField(
            model_name='pos_account_consolidation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pos_account_consolidations', to='financial_app.Wallet'),
        ),
        migrations.AlterField(
            model_name='pos_account_consolidation',
            name='confirmed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='confirmed_by_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pos_account_consolidation',
            name='person_of_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_of_charge_pos', to=settings.AUTH_USER_MODEL),
        ),
    ]
