# Generated by Django 3.0.2 on 2020-07-04 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_payment_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='division',
        ),
    ]
