# Generated by Django 3.0.2 on 2020-02-12 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
        ('payment_app', '0005_remove_payment_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detial',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detials', to='payment_app.Order'),
        ),
        migrations.AlterField(
            model_name='order_detial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product_app.Product'),
        ),
    ]
