# Generated by Django 3.0.2 on 2020-02-12 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
        ('payment_app', '0006_auto_20200212_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detial',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detials', to='payment_app.Order'),
        ),
        migrations.AlterField(
            model_name='order_detial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detials', to='product_app.Product'),
        ),
    ]
