# Generated by Django 3.0.2 on 2020-02-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0007_auto_20200212_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detial',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
