# Generated by Django 3.0.2 on 2020-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0008_order_detial_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detial',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_detial',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='order_detial',
            name='why_deleted',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
