# Generated by Django 3.0.2 on 2020-02-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0009_auto_20200215_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detial',
            name='why_deleted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
