# Generated by Django 3.0.2 on 2020-02-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0010_auto_20200215_1631'),
        ('product_app', '0004_auto_20200215_1631'),
        ('payment_app', '0010_auto_20200215_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detial',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_detials', to='structure_app.Client'),
        ),
        migrations.AlterField(
            model_name='order_detial',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_detials', to='payment_app.Order'),
        ),
        migrations.AlterField(
            model_name='order_detial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_detials', to='product_app.Product'),
        ),
    ]
