# Generated by Django 3.0.2 on 2020-04-25 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0014_auto_20200309_1549'),
        ('payment_app', '0013_auto_20200216_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payments',
            field=models.ManyToManyField(related_name='payments', through='payment_app.Order_payments', to='payment_app.Payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products', through='payment_app.Order_detial', to='product_app.Product'),
        ),
        migrations.AlterField(
            model_name='order_payments',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment_app.Order'),
        ),
        migrations.AlterField(
            model_name='order_payments',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment_app.Payment'),
        ),
    ]
