# Generated by Django 3.0.2 on 2020-05-10 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0020_auto_20200509_1145'),
        ('payment_app', '0014_auto_20200425_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detial',
            name='fr_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_order_detials', to='structure_app.Client'),
        ),
    ]
