# Generated by Django 3.0.2 on 2020-05-16 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0015_order_detial_fr_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detial',
            name='discount_rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
