# Generated by Django 3.0.2 on 2020-06-20 06:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255, null=True)),
                ('program_description', models.TextField(max_length=255, null=True)),
                ('program_favicon_url', models.CharField(max_length=255, null=True)),
                ('program_logo_url', models.CharField(max_length=255, null=True)),
                ('noat_tax', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('capital_city_tax', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hotel_deadline_time_of_dayService', models.CharField(max_length=2, null=True)),
                ('hotel_start_time_of_timeService', models.CharField(max_length=2, null=True)),
                ('hotel_deadline_time_of_timeService', models.CharField(max_length=2, null=True)),
                ('hotel_minimum_time_of_timeService', models.CharField(max_length=2, null=True)),
                ('hotel_must_leave_time', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='division_createdby', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(db_table='auth_user_divisions', related_name='divisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fr_worker_confirm', models.BooleanField(default=0)),
                ('to_worker_confirm', models.BooleanField(default=0)),
                ('controller_confirm', models.BooleanField(default=0)),
                ('finished', models.BooleanField(default=0)),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='controller_shift_workers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_work_createdby', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Shift_works', to='structure_app.Division')),
                ('fr_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fr_shift_workers', to=settings.AUTH_USER_MODEL)),
                ('to_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_shift_workers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('firstname', models.CharField(max_length=255)),
                ('register', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('address2', models.CharField(default='', max_length=255, null=True)),
                ('workname', models.CharField(default='', max_length=255, null=True)),
                ('workaddress', models.CharField(default='', max_length=255, null=True)),
                ('mobile', models.IntegerField(blank=True, default=0, null=True)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.EmailField(blank=True, default=0, max_length=254, null=True)),
                ('discount_rate', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('information', models.TextField(default='', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_createdby', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('register', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255, null=True)),
                ('mobile', models.IntegerField()),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('information', models.TextField(null=True)),
                ('who_are', models.CharField(blank=True, max_length=10, null=True)),
                ('near_people_name', models.CharField(blank=True, max_length=30, null=True)),
                ('near_people_mobile', models.IntegerField(blank=True, null=True)),
                ('near_people_address', models.CharField(blank=True, max_length=255, null=True)),
                ('school1', models.CharField(max_length=100)),
                ('school2', models.CharField(max_length=100)),
                ('school3', models.CharField(max_length=100)),
                ('citizen_identity_card_copy', models.BooleanField(default=0)),
                ('white_card_of_hospital', models.BooleanField(default=0)),
                ('number_of_white_card', models.CharField(max_length=30, null=True)),
                ('social_security_book', models.BooleanField(default=0)),
                ('number_of_social_security_book', models.CharField(max_length=30, null=True)),
                ('health_book', models.BooleanField(default=0)),
                ('number_of_health_book', models.CharField(max_length=30, null=True)),
                ('first_contract', models.BooleanField(default=0)),
                ('number_of_first_contract', models.CharField(max_length=30, null=True)),
                ('second_contract', models.BooleanField(default=0)),
                ('number_of_second_contract', models.CharField(max_length=30, null=True)),
                ('first_salary', models.BigIntegerField(blank=True, null=True)),
                ('second_salary', models.BigIntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=30, null=True)),
                ('account_of_bank', models.BigIntegerField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars/%Y%m%d%H%H%S')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile_createdby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('register', 'mobile')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('number', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('free', models.BooleanField(default=1)),
                ('clean', models.BooleanField(default=1)),
                ('minibarFull', models.BooleanField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_createdby', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='structure_app.Division')),
            ],
            options={
                'unique_together': {('division', 'number')},
            },
        ),
    ]
