# Generated by Django 3.0.2 on 2020-02-11 09:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('number', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_createdby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_client_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices_type', models.CharField(choices=[('0', '---'), ('1', 'Зочины мэдээлэл'), ('2', 'Цэвэрлэгээний мэдээлэл'), ('3', 'Мини барны мэдээлэл')], default=0, max_length=3)),
                ('login_info_choices', models.CharField(choices=[('0', '---'), ('in', 'Зочин орсон'), ('out', 'Зочин гарсан')], default=0, max_length=3)),
                ('cleaning_info_choices', models.CharField(choices=[('0', '---'), ('c_s', 'Цэвэрлэж эхэлсэн'), ('c_e', 'Цэвэрлэж дууссан')], default=0, max_length=3)),
                ('bar_refilled_info_choices', models.CharField(choices=[('0', '---'), ('b_r', 'Мини бар цэнэглэгдсэн'), ('b_u', 'Мини бар цэнэглэгдээгүй')], default=0, max_length=3)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('limit_time', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='structure_app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='division_createdby', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(db_table='auth_user_divisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure_app.Division'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('register', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('workaddress', models.CharField(max_length=255)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('discount_rate', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('information', models.TextField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_createdby', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('register', 'mobile')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('division', 'number')},
        ),
    ]
