# Generated by Django 3.0.2 on 2020-06-21 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift_work',
            old_name='fr_worker_confirm',
            new_name='worker_confirm',
        ),
        migrations.RemoveField(
            model_name='shift_work',
            name='fr_worker',
        ),
        migrations.RemoveField(
            model_name='shift_work',
            name='to_worker',
        ),
        migrations.RemoveField(
            model_name='shift_work',
            name='to_worker_confirm',
        ),
        migrations.AddField(
            model_name='shift_work',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_works', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shift_work',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='controller_shift_works', to=settings.AUTH_USER_MODEL),
        ),
    ]
