# Generated by Django 3.0.2 on 2020-02-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_client_log',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='structure_app.Client'),
        ),
    ]
