# Generated by Django 3.0.2 on 2020-02-11 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure_app', '0002_auto_20200211_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_client_log',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='structure_app.Client'),
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('register', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('information', models.TextField(null=True)),
                ('who_are', models.CharField(blank=True, max_length=10, null=True)),
                ('near_people_name', models.CharField(blank=True, max_length=30, null=True)),
                ('near_people_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('near_people_address', models.CharField(blank=True, max_length=255, null=True)),
                ('school1', models.CharField(max_length=100)),
                ('school2', models.CharField(max_length=100)),
                ('school3', models.CharField(max_length=100)),
                ('citizen_identity_card_copy', models.BooleanField(default=0)),
                ('white_card_of_hospital', models.BooleanField(default=0)),
                ('number_of_white_card', models.CharField(max_length=255, null=True)),
                ('social_security_book', models.BooleanField(default=0)),
                ('number_of_social_security_book', models.CharField(max_length=255, null=True)),
                ('health_book', models.BooleanField(default=0)),
                ('number_of_health_book', models.CharField(max_length=255, null=True)),
                ('first_contract', models.BooleanField(default=0)),
                ('second_contract', models.BooleanField(default=0)),
                ('first_salary', models.BigIntegerField(blank=True, null=True)),
                ('second_salary', models.BigIntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=30, null=True)),
                ('account_of_bank', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile_createdby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('register', 'mobile')},
            },
        ),
    ]
