# Generated by Django 3.0.2 on 2020-02-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0003_auto_20200211_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='number_of_first_contract',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='number_of_second_contract',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='number_of_health_book',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='number_of_social_security_book',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='number_of_white_card',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
