# Generated by Django 3.0.2 on 2020-02-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0004_auto_20200211_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars/%Y%m%d%H%H%S'),
        ),
    ]
