# Generated by Django 3.0.2 on 2020-02-12 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0005_user_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255, null=True)),
                ('program_description', models.CharField(max_length=255, null=True)),
                ('program_favicon_url', models.CharField(max_length=255, null=True)),
                ('noat_tax', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('capital_city_tax', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
