# Generated by Django 3.0.2 on 2020-02-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0006_configuration_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration_value',
            name='program_logo_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
