# Generated by Django 3.0.2 on 2020-02-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0007_configuration_value_program_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration_value',
            name='program_description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
