# Generated by Django 3.0.2 on 2020-02-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0008_auto_20200212_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel_client_log',
        ),
    ]
