# Generated by Django 3.0.2 on 2020-03-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0010_auto_20200215_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration_value',
            name='hotel_deadline_time_of_dayService',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='configuration_value',
            name='hotel_deadline_time_of_timeService',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='configuration_value',
            name='hotel_minimum_time_of_timeService',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
