# Generated by Django 3.0.2 on 2020-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0011_auto_20200315_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration_value',
            name='hotel_must_leave_time',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
