# Generated by Django 3.0.2 on 2020-05-09 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure_app', '0019_auto_20200425_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='users',
            field=models.ManyToManyField(db_table='auth_user_divisions', related_name='divisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
