# Generated by Django 3.0.2 on 2020-06-20 06:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('status', models.CharField(default='Төсөвлөсөн', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('country', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('investor', models.CharField(max_length=255)),
                ('issued_money', models.DecimalField(decimal_places=2, max_digits=14)),
                ('refunded_money', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('issued_date', models.DateTimeField(blank=True, null=True)),
                ('refunded_date', models.DateTimeField(blank=True, null=True)),
                ('will_refund', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('lender', models.CharField(max_length=255)),
                ('issued_money', models.DecimalField(decimal_places=2, max_digits=14)),
                ('refunded_money', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('loan_rate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('issued_date', models.DateTimeField(blank=True, null=True)),
                ('refunded_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Money_transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('msg_info_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('transfer_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('description', models.TextField(null=True)),
                ('wanna_delete', models.BooleanField(default=0)),
                ('recieved_ebarimt', models.BooleanField(default=0)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('bank', models.CharField(max_length=255, null=True)),
                ('account', models.BigIntegerField(null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('msg_info_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('transfer_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('bank_transfer_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet_createdby', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Money_transfer_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='money_transfer_type_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
