# Generated by Django 3.0.2 on 2020-06-20 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_app', '0001_initial'),
        ('structure_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='money_transfer',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment_app.Bill'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='money_transfer_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='financial_app.Currency'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='structure_app.Customer'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='structure_app.Division'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='fr_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fr_budget', to='financial_app.Budget'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='fr_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fr_investment', to='financial_app.Investment'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='fr_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fr_loan', to='financial_app.Loan'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='fr_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moneytransfer_fr_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='fr_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fr_wallet', to='financial_app.Wallet'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='money_transfer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financial_app.Money_transfer_type'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment_app.Payment'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='to_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_budget', to='financial_app.Budget'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='to_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_investment', to='financial_app.Investment'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='to_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_loan', to='financial_app.Loan'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moneytransfer_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='to_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_wallet', to='financial_app.Wallet'),
        ),
        migrations.AddField(
            model_name='money_transfer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='money_transfer_modifiedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='investment_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget_type',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='budget_type_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='budget_type', to='financial_app.Budget_type'),
        ),
        migrations.AddField(
            model_name='budget',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='budget_coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='budget_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='budget_modifiedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
