# Generated by Django 3.0.2 on 2020-07-05 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0002_auto_20200621_1448'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_app', '0002_auto_20200620_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallets', to='structure_app.Division'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
    ]
